version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: devops-group
      - run:
          name: Build React App
          command: |
            cd devops-group
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - devops-group

  test:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run All Tests
          command: |
            cd devops-group
            npm run test:ci

  security-scan:
    docker:
      - image: owasp/zap2docker-stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run OWASP ZAP Scan
          command: |
            cd scripts
            ./zap-test.sh
      - store_artifacts:
          path: zap-report.html
          destination: zap-report

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to EC2
          command: |
            ssh -i $SSH_KEY_FILE $EC2_USERNAME@$EC2_HOST "cd devops-group && ./deploy.sh"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - security-scan:
          requires:
            - test
      - approve-deployment:
          type: approval
          requires:
            - security-scan
      - deploy:
          requires:
            - approve-deployment