version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main

jobs:
  build:
    working_directory: ~/devops-group/devops-group
    docker:
      - image: cimg/node:10.8.2
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@10.8.2'
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: CI=false npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - server.js