version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main

jobs:
  build:
    working_directory: ~/devops-group
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout:
          path: ~/devops-group
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: CI=false npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - server.js