version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - approve-deployment:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - approve-deployment

jobs:
  build:
    working_directory: ~/devops-group
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: CI=false npm run build