version: 2.1

orbs:
  node: circleci/node@5.0.2
  slack: circleci/slack@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd devops-group
            npm ci
      - run:
          name: Build React App
          command: |
            cd devops-group
            CI=false npm run build
      - persist_to_workspace:
          root: .
          paths:
            - devops-group

  security-scan:
    docker:
      - image: owasp/zap2docker-stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run OWASP ZAP Scan
          command: |
            cd scripts
            ./zap-test.sh
      - store_artifacts:
          path: zap-report.html
          destination: zap-report
      - persist_to_workspace:
          root: .
          paths:
            - zap-report.html

  prepare-deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Prepare Deployment Checklist
          command: |
            echo "Deployment Checklist:" > deployment-checklist.txt
            echo "1. Build completed successfully: ✓" >> deployment-checklist.txt
            echo "2. Security scan completed: ✓" >> deployment-checklist.txt
            echo "3. Changes in this build:" >> deployment-checklist.txt
            git log -1 --pretty=format:"%h - %an, %ar : %s" >> deployment-checklist.txt
            echo "4. Attached ZAP security report" >> deployment-checklist.txt
      - persist_to_workspace:
          root: .
          paths:
            - deployment-checklist.txt

workflows:
  version: 2
  build-scan-deploy:
    jobs:
      - build
      - security-scan:
          requires:
            - build
      - prepare-deployment:
          requires:
            - security-scan
      - approve-deployment:
          type: approval
          requires:
            - prepare-deployment
      - slack/on-hold:
          requires:
            - prepare-deployment
          context: slack-secrets
          channel: devops-deployments
          template: basic_on_hold_1